name: ASP.NET CI
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: MSBuild
      working-directory: src
      run: msbuild Pablito.csproj
